name: Python

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install radare2 5.8.0
      run: |
        wget https://github.com/radareorg/radare2/releases/download/5.8.0/radare2_5.8.0_amd64.deb
        sudo dpkg -i radare2_5.8.0_amd64.deb
    - name: Install python dependencies
      run: pip3 install -r python/requirements_ci.txt
    - name: Build python module
      run: cd python && sudo ./setup.py install
